### ISSUE TITLE
Should business logic be validated in the Service, or in the DTO?

### ISSUE THREAD

**Issue by JoshuaAndrea** [DennisDoksani/Code_Generation_2223k#57]
We have RegistrationDTO

```
public record RegistrationDTO(
    @NotBlank(message="BSN is required.") String bsn, 
    @NotBlank(message="Email is required.") @Email(message="Email is invalid.") String email, 
    @NotBlank(message="Password is required.") String password,  
    @NotBlank(message="First name is required.") String firstName,  
    @NotBlank(message="Last name is required.") String lastName,  
    @NotBlank(message="Phone number is required.") String phoneNumber,  
    @NotBlank(message="Date of Birth is required.") @Past LocalDate dateOfBirth){}
```

Business logic states that new users who are registered should not be younger than 18 years old.

```
//Check if date is further than 18 years ago
if (dateofBirth.isAfter(LocalDate.now().minusYears(18)))
      throw new IllegalArgumentException("User must be at least 18 years old");
```

Should this be checked on RegistrationDTO level, or should we check it later on in the UserService?

**Comment by ahrnuld** [comment]
In my opinion: it depends on whether you think checking the age is part of

- Valid user registration data (technical requirements to data to enable storage in the database)
- The user registration process (business rules requirements to data)

I think this is a case of the latter, and then it should be with the other business logic: in the service.

If this was a real banking system, I think such requirements would be checked by business rule classes, perhaps even using the OOP strategy pattern or even a separate business rule system. These would also be called from the service classes. However, that is out of scope for now.
